### ISSUE TITLE
Any chance for new stable release?

### ISSUE THREAD

**Issue by debach** [symfony-cmf/create-bundle#151]
I happily use the CreateBundle at dev-master, taking advantage of the ORM support. Though, it would be nice if we had a stable release, 1.3 or whatever.

**Comment by dbu** [comment]
indeed, seems things are ready. created https://github.com/symfony-cmf/create-bundle/releases/tag/1.3.0

note that active development of this bundle has stopped, as we lack resources in the symfony cmf project and need to focus on the core bundles. so a symfony 3 upgrade for example is not planned. if you want to pick this up, we are more than happy to make you maintainer of the CreateBundle.
