### ISSUE TITLE
RoleAccessChecker is not being injected with the correct services

### ISSUE THREAD

**Issue by jon-frankel** [symfony-cmf/create-bundle#154]
\Symfony\Cmf\Bundle\CreateBundle\Security\RoleAccessChecker has a constructor that takes four arguments:

    /**
     * @param string                             $requiredRole         The role to check with the security
     *                                                                 context.
     * @param TokenStorageInterface|null         $tokenStorage         If null is passed, check will always
     *                                                                 return false.
     * @param AuthorizationCheckerInterface|null $authorizationChecker If null is passed, check will always
     *                                                                 return false.
     * @param LoggerInterface                    $logger               The logger to log exceptions from the
     *                                                                 security context.
     */

However, the services config file is injecting the wrong parameters:

    <service id="cmf_create.security.role_access_checker" class="%cmf_create.security.role_access_checker.class%">
        <argument>%cmf_create.security.role%</argument>
        <argument type="service" id="security.context" on-invalid="ignore"/>
        <argument type="service" id="logger"/>
    </service>

I think this may be related to #140? I'm not sure since the description in that is kind of spare. I'm going to create a PR with a fix for this.

**Comment by dbu** [comment]
fixed in #155
